name: BloodyEnvoys
authors: ["Vanic"]
description: BloodyEnvoys
api: [5.0.0]
version: 1.1.0
main: Vanic\Bloody\Envoys\Main
load: POSTWORLD
softdepend:
  - BedrockEconomy
  - EconomyAPI
  - Capital
